"""Interactive setup wizard: `polycopy-setup`.

Asks for the handful of details the bot needs and writes a complete .env, so
operators never hand-edit config. Cross-platform (Linux / macOS / Windows
PowerShell) — pure stdlib + cryptography (already a dependency).
"""

import secrets
from pathlib import Path

from cryptography.fernet import Fernet

# (key, default, comment) — defaults used when the operator just presses Enter.
ENV_SPEC: list[tuple[str, str, str]] = [
    ("APP_ENV", "prod", "dev | prod"),
    ("TELEGRAM_BOT_TOKEN", "", "from @BotFather"),
    ("TELEGRAM_BOT_USERNAME", "", "bot username without @ (for the web login widget)"),
    ("DATABASE_URL", "sqlite+aiosqlite:///./polycopy.db", "sqlite for dev, postgres for prod"),
    ("FERNET_KEY", "", "encrypts stored keys at rest"),
    ("APP_SECRET", "", "signs dashboard session tokens"),
    ("POLYMARKET_DATA_API", "https://data-api.polymarket.com", ""),
    ("POLYMARKET_CLOB_API", "https://clob.polymarket.com", ""),
    ("POLYMARKET_GAMMA_API", "https://gamma-api.polymarket.com", ""),
    ("POLYMARKET_LB_API", "https://lb-api.polymarket.com", ""),
    ("POLYGON_RPC", "https://polygon-rpc.com", ""),
    ("POLYGON_CHAIN_ID", "137", ""),
    ("WATCHER_POLL_INTERVAL", "15", "seconds between checks for new leader trades"),
    ("SCOUT_POLL_INTERVAL", "3600", "seconds between leaderboard rescans"),
    ("RECONCILE_POLL_INTERVAL", "30", "seconds between order-fill checks"),
    ("NEXT_PUBLIC_API_URL", "http://localhost:8000", "browser-reachable API URL for the web app"),
    ("NEXT_PUBLIC_TELEGRAM_BOT_USERNAME", "", "bot username for the dashboard login widget"),
]


def generate_fernet_key() -> str:
    return Fernet.generate_key().decode()


def generate_secret() -> str:
    return secrets.token_urlsafe(48)


def find_project_root(start: Path | None = None) -> Path:
    """Walk up from `start` to the dir holding .env.example (the repo root)."""
    here = (start or Path.cwd()).resolve()
    for path in (here, *here.parents):
        if (path / ".env.example").exists() or (path / "docker-compose.yml").exists():
            return path
    return here


def render_env(values: dict[str, str]) -> str:
    lines = ["# Generated by polycopy-setup. Safe to edit by hand.", ""]
    for key, _default, comment in ENV_SPEC:
        if comment:
            lines.append(f"# {comment}")
        lines.append(f"{key}={values.get(key, '')}")
    return "\n".join(lines) + "\n"


def _ask(prompt: str, default: str = "", secret_default: str = "") -> str:
    suffix = f" [{default}]" if default else (" [auto-generate]" if secret_default else "")
    raw = input(f"{prompt}{suffix}: ").strip()
    if raw:
        return raw
    return default or secret_default


def main() -> None:
    print("\n=== Polycopy setup ===")
    print("Press Enter to accept the [default]. Ctrl-C to abort.\n")

    root = find_project_root()
    env_path = root / ".env"
    if env_path.exists() and input(
        f"{env_path} already exists. Overwrite? [y/N]: "
    ).strip().lower() != "y":
        print("Aborted — existing .env left untouched.")
        return

    values: dict[str, str] = {key: default for key, default, _c in ENV_SPEC}

    print("--- Telegram ---")
    values["TELEGRAM_BOT_TOKEN"] = _ask("Bot token (from @BotFather)")
    while not values["TELEGRAM_BOT_TOKEN"]:
        print("  A bot token is required. Create a bot with @BotFather, then paste its token.")
        values["TELEGRAM_BOT_TOKEN"] = _ask("Bot token")
    username = _ask("Bot username (without @, optional)")
    values["TELEGRAM_BOT_USERNAME"] = username
    values["NEXT_PUBLIC_TELEGRAM_BOT_USERNAME"] = username

    print("\n--- Database ---")
    choice = _ask("Use [1] SQLite (easy, single file) or [2] PostgreSQL", "1")
    if choice == "2":
        values["DATABASE_URL"] = _ask(
            "PostgreSQL URL",
            "postgresql+asyncpg://polycopy:polycopy@localhost:5432/polycopy",
        )
    else:
        values["DATABASE_URL"] = "sqlite+aiosqlite:///./polycopy.db"

    print("\n--- Secrets (auto-generated; just press Enter) ---")
    values["FERNET_KEY"] = _ask("Fernet key", secret_default=generate_fernet_key())
    values["APP_SECRET"] = _ask("App secret", secret_default=generate_secret())

    print("\n--- Web dashboard ---")
    values["NEXT_PUBLIC_API_URL"] = _ask(
        "Browser-reachable API URL", values["NEXT_PUBLIC_API_URL"]
    )

    env_path.write_text(render_env(values), encoding="utf-8")
    print(f"\n✅ Wrote {env_path}")
    print("\nNext steps — run each in its own terminal from the backend/ folder:")
    print("  polycopy-api        # http://localhost:8000")
    print("  polycopy-bot")
    print("  polycopy-worker")
    print("\nThen open the bot in Telegram and send /start.\n")


if __name__ == "__main__":
    main()
