"""initial schema

Revision ID: 25239ccd3168
Revises: 
Create Date: 2026-05-27 20:49:15.980114
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '25239ccd3168'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('volume_usd', sa.Float(), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traders_wallet'), ['wallet'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('default_size_pct', sa.Float(), nullable=False),
    sa.Column('max_slippage_bps', sa.BigInteger(), nullable=False),
    sa.Column('max_notional_per_trade_usd', sa.Float(), nullable=False),
    sa.Column('daily_spend_cap_usd', sa.Float(), nullable=False),
    sa.Column('auto_scout_enabled', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('paper_trading', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('copied_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.String(length=128), nullable=False),
    sa.Column('market_question', sa.String(length=512), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('leader_tx_hash', sa.String(length=80), nullable=True),
    sa.Column('leader_price', sa.Float(), nullable=False),
    sa.Column('leader_size', sa.Float(), nullable=False),
    sa.Column('our_order_id', sa.String(length=128), nullable=True),
    sa.Column('our_price', sa.Float(), nullable=True),
    sa.Column('our_size', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('skip_reason', sa.String(length=256), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copied_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copied_trades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_copied_trades_leader_tx_hash'), ['leader_tx_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_copied_trades_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_copied_trades_trader_id'), ['trader_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_copied_trades_user_id'), ['user_id'], unique=False)

    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('size_pct_override', sa.Float(), nullable=True),
    sa.Column('max_slippage_bps_override', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trader_id', name='uq_follow_user_trader')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follows_trader_id'), ['trader_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_user_id'), ['user_id'], unique=False)

    op.create_table('polymarket_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proxy_address', sa.String(length=64), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.Column('api_secret_enc', sa.String(length=512), nullable=False),
    sa.Column('api_passphrase_enc', sa.String(length=512), nullable=False),
    sa.Column('private_key_enc', sa.String(length=512), nullable=False),
    sa.Column('signature_type', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('watcher_cursors',
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('last_trade_ts', sa.DateTime(), nullable=True),
    sa.Column('last_trade_hash', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('trader_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watcher_cursors')
    op.drop_table('polymarket_credentials')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_user_id'))
        batch_op.drop_index(batch_op.f('ix_follows_trader_id'))

    op.drop_table('follows')
    with op.batch_alter_table('copied_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copied_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_copied_trades_trader_id'))
        batch_op.drop_index(batch_op.f('ix_copied_trades_market_id'))
        batch_op.drop_index(batch_op.f('ix_copied_trades_leader_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_copied_trades_created_at'))

    op.drop_table('copied_trades')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traders_wallet'))

    op.drop_table('traders')
    # ### end Alembic commands ###
